### ISSUE TITLE
What is daemon_pi.py going to do?

### ISSUE THREAD

**Issue by canbula** [canbula/ParallelProgramming.2022.2023.Fall#14]
The main purpose of this program is using a daemon thread running in background and improving the precision of the estimation of the value of pi by using Monte Carlo simulation. The program should satisfy the following requirements:

- The user is asked for the value of the radius of a circle and calculates the area of the circle by using pi and radius values.
- The program ends if user gives "q" as the radius.
- More our user waits, our estimation for the value of pi becomes more precise.
- If program ends, the thread created with DaemonPi should not block the program, therefore it should be daemon thread.

Good luck.

https://github.com/canbula/ParallelProgramming.2022.2023.Fall/blob/8a7ae01e4597aaa44ac58a03d4fa1fca2f82d058/Week08/midterm/daemon_pi.py

**Comment by umitguner2002** [comment]
import threading
import random


class DaemonPi(threading.Thread):
    def __init__(self):
        super().__init__(daemon = True)
        self._inner = 0
        self._total = 0
        self._lock = threading.Lock()

    def run(self):
        while True:
            x = random.uniform(-1, 1)
            y = random.uniform(-1, 1)
            with self._lock:
                self._total += 1
                if x ** 2 + y ** 2 <= 1:
                    self._inner += 1

    def pi(self):
        return 4 * self._inner / self._total

def main():
    pi_thread = DaemonPi()
    pi_thread.start()
    while True:
        radius = input("Enter radius: ")
        if radius == "q":
            break
        print(f"Pi is estimated as {pi_thread.pi()}")
        print(f"Area of circle with radius {radius} is "
              f"{pi_thread.pi() * float(radius) ** 2}")

if __name__ == '__main__':
    main()

**Comment by canbula** [comment]
I am very happy with the result, thank you for the contributions.
