### ISSUE TITLE
Parallelize the loop with a decorator

### ISSUE THREAD

**Issue by canbula** [canbula/ParallelProgramming.2022.2023.Fall#19]
I have a password for you to crack. The passwd string is hashed twice with md5 algorithm. The only information we have about password is that it is an eight digit integer. Therefore we have a loop within the range [10000000:99999999] in the function guess_the_password. It is a very large interval to cover so we need to use every core that we have in our PCs. Therefore you need to distribute the loop to your cores by using threading module. I don't want you to change the function so solve this problem by using the decorator.

https://github.com/canbula/ParallelProgramming.2022.2023.Fall/blob/bb36e676a91129260086d05f9c662d9bb87a1bf8/Week08/midterm/parallel_loop.py#L10-L13

**Comment by akincan-kilic** [comment]
How can we utilize every core of our CPUs if we don't use `numba`?

To bypass the **GIL (Global Interpreter Lock)** we need to remove all Pythonic code, but since the cracker algorithm depends on the `text_to_md5()` function, we cannot turn our core loop into non-python.

What should we do?

**Comment by canbula** [comment]
> How can we utilize every core of our CPUs without using `numba`?
> 
> To bypass the **GIL (Global Interpreter Lock)** we need to use `numba`, which in turn asks for us to remove all Pythonic code, but since the password cracking algorithm depends on the `text_to_md5()` function, we cannot turn our core loop into non-python.
> 
> What should we do?

I believe in you, you can find a way :)
