### ISSUE TITLE
"add_chocolate_chips" function in "cookie.py" doesn't occupy chef.

### ISSUE THREAD

**Issue by FerhatStl** [canbula/ParallelProgramming.2022.2023.Fall#20]
The function named as add_chocolate_chips needs to occupy chef while working but it doesn't.
Original Code:
![resim_2022-11-20_145843044](https://user-images.githubusercontent.com/97604027/202900639-9c0e57b7-3dae-499e-8938-01a0b12b12c5.png)

Fixed Version:
![resim_2022-11-20_145954339](https://user-images.githubusercontent.com/97604027/202900693-c8e974aa-b3ea-4030-9b38-05bdf0b1e265.png)

**Comment by canbula** [comment]
Commit the changes please
