### ISSUE TITLE
Make the variables private

### ISSUE THREAD

**Issue by canbula** [canbula/ParallelProgramming.2022.2023.Fall#8]
Turn the variables self.inner and self.total into private variables.

https://github.com/canbula/ParallelProgramming.2022.2023.Fall/blob/8a7ae01e4597aaa44ac58a03d4fa1fca2f82d058/Week08/midterm/daemon_pi.py#L9-L10

**Comment by damlaYasarr** [comment]
self.__inner=0 
self.__total=0  
double underscore makes the variable private.

**Comment by canbula** [comment]
Issue closed with this final commit

https://github.com/canbula/ParallelProgramming.2022.2023.Fall/commit/63c47f9071cf171fd8dd31619cb1a59e9ef0e872
